// SPDX-License-Identifier: MIT
//
// Headless post-script that remaps a raw decompressed 3DS .code import into
// NCCH ExHeader code-set blocks using a payload-free manifest generated by
// extract-cxi-exefs.ps1.

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.mem.MemoryBlock;

import java.io.ByteArrayInputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;

public class MapCtrCodeSet extends GhidraScript {

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            throw new IllegalArgumentException("Usage: MapCtrCodeSet.java <manifest.structure.json> [--init-bss] [--disable-switch-analysis]");
        }
        boolean initializeBss = false;
        boolean disableSwitchAnalysis = false;
        for (String arg : args) {
            if ("--init-bss".equals(arg)) {
                initializeBss = true;
            }
            if ("--disable-switch-analysis".equals(arg)) {
                disableSwitchAnalysis = true;
            }
        }
        if (disableSwitchAnalysis) {
            setAnalysisOption(currentProgram, "Decompiler Switch Analysis", "false");
        }

        JsonObject manifest = JsonParser.parseString(Files.readString(Paths.get(args[0]))).getAsJsonObject();
        JsonObject codeSet = manifest.getAsJsonObject("code_set");

        MemoryBlock raw = currentProgram.getMemory().getBlock("ram");
        if (raw == null) {
            MemoryBlock[] blocks = currentProgram.getMemory().getBlocks();
            if (blocks.length != 1) {
                throw new IllegalStateException("Expected one raw import block, found " + blocks.length);
            }
            raw = blocks[0];
        }

        if (raw.getSize() > Integer.MAX_VALUE) {
            throw new IllegalStateException("Raw .code block is too large to remap in one pass");
        }

        byte[] code = new byte[(int) raw.getSize()];
        currentProgram.getMemory().getBytes(raw.getStart(), code);
        currentProgram.getMemory().removeBlock(raw, monitor);

        Segment text = segment(codeSet.getAsJsonObject("text"));
        Segment rodata = segment(codeSet.getAsJsonObject("rodata"));
        Segment data = segment(codeSet.getAsJsonObject("data"));
        JsonObject bss = codeSet.getAsJsonObject("bss");

        boolean aligned = text.size + rodata.size + data.size < code.length;
        int offset = 0;
        offset = createInitialized(".text", text, aligned, code, offset, true, false, true);
        offset = createInitialized(".rodata", rodata, aligned, code, offset, true, false, false);
        offset = createInitialized(".data", data, aligned, code, offset, true, true, false);

        long bssSize = bss.get("size").getAsLong();
        if (bssSize > 0) {
            Address bssAddress = addr(bss.get("address_value").getAsLong());
            MemoryBlock block;
            if (initializeBss) {
                block = currentProgram.getMemory().createInitializedBlock(".bss", bssAddress, bssSize, (byte) 0, monitor, false);
            } else {
                block = currentProgram.getMemory().createUninitializedBlock(".bss", bssAddress, bssSize, false);
            }
            block.setRead(true);
            block.setWrite(true);
            block.setExecute(false);
        }
    }

    private int createInitialized(String name, Segment segment, boolean aligned, byte[] code, int offset, boolean read, boolean write, boolean execute) throws Exception {
        int size = (int) segment.size;
        int consumed = (int) (aligned ? segment.physicalSize : segment.size);
        if (size == 0) {
            return offset + consumed;
        }
        if (offset + consumed > code.length) {
            throw new IllegalStateException(name + " exceeds decompressed .code size");
        }

        byte[] bytes = Arrays.copyOfRange(code, offset, offset + size);
        MemoryBlock block = currentProgram.getMemory().createInitializedBlock(
            name,
            addr(segment.address),
            new ByteArrayInputStream(bytes),
            bytes.length,
            monitor,
            false
        );
        block.setRead(read);
        block.setWrite(write);
        block.setExecute(execute);
        return offset + size;
    }

    private Segment segment(JsonObject json) {
        return new Segment(
            json.get("address_value").getAsLong(),
            json.get("physical_size").getAsLong(),
            json.get("size").getAsLong()
        );
    }

    private Address addr(long value) {
        return currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(value);
    }

    private static class Segment {
        final long address;
        final long physicalSize;
        final long size;

        Segment(long address, long physicalSize, long size) {
            this.address = address;
            this.physicalSize = physicalSize;
            this.size = size;
        }
    }
}
